- name: Installing Catalogue Component
  hosts: catalogue
  become: yes
  tasks:
  - name: Setting up NPM source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Installing NodeJS
    ansible.builtin.yum:
      name: nodejs 
      state: installed
  - name: Checking if the roboshop user is existed or not
    ansible.builtin.command: id username
    register: out
    ignore_errors: true

  - name: Creating RoboShop user if it does not exist
    when: out.rc !=0
    ansible.builtin.user:
      name: roboshop

  - name: Setup an app directory
    ansible.builtin.file:
      path: /app
      register: directory
