- name: Installing Catalogue Component
  hosts: catalogue
  become: yes
  tasks:
  - name: Setting up NPM source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Installing NodeJS
    ansible.builtin.yum:
      name: nodejs 
      state: installed
  - name: Creating roboshop username
    ansible.builtin.shell: "id username"
    register: out
    ignore_errors: true
