- name: Installing Catalogue Component
  hosts: catalogue
  become: yes
  tasks:
  - name: Setting up NPM source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Installing NodeJS
    ansible.builtin.yum:
      name: nodejs 
      state: installed
  - name: Checking if the roboshop user is existed or not
    ansible.builtin.command: 
      id roboshop
    register: out
    ignore_errors: true

  - name: Creating RoboShop user if it does not exist
    when: out.rc !=0
    ansible.builtin.user:
      name: roboshop

  - name: Check if a directory is exist or not
    ansible.builtin.stat:
      path: /app
    register: directory
    ignore_errors: true

  - name: Printing
    ansible.builtin.debug:
      msg: "{{directory}}"

  - when: directory.stat.exists == false
    name: Creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory  

  - name: Download the application code to created app directory.
    ansible.builtin.get_url: 
       url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
       dest: /tmp

  - name: unarchiving 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app