- name: Installing MongoDB component
  hosts: mongodb
  become: yes
  tasks:
  - name: Install MongoDB
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
   
  - name: Enabling MongoDB
    ansible.builtin.service:
      name: mongodb-org
      enabled: yes
    
  - name: Starting MongoDB
    ansible.builtin.service:
      name: mongodb-org
      state: started

