- name: Setting up Web Component
  hosts: web
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.yum:
      name: nginx
      state: installed

  - name: Enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
